version: "3"
services:
  ros-kobuki:
    image: j3soon/ros-melodic-kobuki
    container_name: ros-melodic-kobuki
    devices:
      - /dev/kobuki:/dev/kobuki
    working_dir: "/root/catkin_ws"
    command: |-
      bash -c "
      cd ~/catkin_ws &&
      source ./devel/setup.bash &&
      sleep infinity
      "
