FROM arm64v8/ros:melodic

# Install kobuki
COPY thirdparty/install_basic.sh /root/catkin_ws/install_basic.sh
RUN . /opt/ros/melodic/setup.sh && \
    mkdir -p ~/catkin_ws/src && \
    cd ~/catkin_ws && \
    apt-get update && \
    bash install_basic.sh && \
    apt-get install -y ros-melodic-urdf ros-melodic-gazebo-ros-pkgs ros-melodic-depth-image-proc ros-melodic-xacro && \
    catkin_make && \
    rm -rf /var/lib/apt/lists/*
